name: CD-Deploy
on:
  push:
    branches:
      - 'develop'
#    paths:
#      - '06-best-practices/code/**'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3