name: CI-Tests
on:
    pull_request:
      branches:
        - 'develop'
      paths:
        - 'code/**'


env:
    AWS_DEFAULT_REGION: 'eu-west-2'
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
    test:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2       # github actions
          - name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
              python-version: 3.9   

          - name: Install dependencies
            working-directory: "code"
            run: pip install pipenv && pipenv install --dev

          - name: Run Unit tests
            working-directory: "code"
            run: pipenv run pytest tests/
    
          - name: Lint
            working-directory: "code"
            run: pipenv run pylint --recursive=y .

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_DEFAULT_REGION }}

          #- name: Integration Test
          #  working-directory: 'code/integraton-test'
          #  run: |
          #    . run.sh

    tf-plan:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}
  
        - uses: hashicorp/setup-terraform@v2
        
        # reconfigure key without modifying the existing code
        - name: TF plan
          id: plan
          working-directory: 'code/infrastructure'
          run: |
            terraform init -backend-config="key=mlops-zoomcamp-prod.tfstate" --reconfigure && terraform plan --var-file vars/prod.tfvars

